name: simple_shopping
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  go_router: ^14.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  skeletonizer: ^1.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/generated/
